apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Jasper Gateway Plugin
  description: Gateway Plugin to ingest events forwarded by Jasper through it's Push API
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - gateway
    - jasper
  config:
    url:
      label: URL
      type: String
      maxLength: 1000
      required: false
      default: /events
      help: "(Optional) The path where events will get POSTed to. Default: /events."
    sharedSecret:
      label: Push API Shared Secret
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) When supplied, all data will be verified the specified value."

  loadBalancing:
    method: http
    enableSticky: true

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??